# LifeTrace 默认配置文件

# 基础设置
# base_dir: ~/.lifetrace
base_dir: C:\Users\PC\.lifetrace
database_path: lifetrace.db
screenshots_dir: screenshots

# 服务器配置
server:
  host: 127.0.0.1
  port: 8840
  debug: false

# 截图记录配置
record:
  # interval: 10  # 截图间隔（秒）
  # screens: "all"  # 截图屏幕：all 或屏幕编号列表
  interval: 3
  screens: [3]
  format: png  # 截图格式：png, jpg
  quality: 85  # JPG质量（1-100）
  # 超时配置（秒）
  file_io_timeout: 15  # 文件I/O操作超时
  db_timeout: 20  # 数据库操作超时
  window_info_timeout: 5  # 获取窗口信息超时

# OCR配置
ocr:
  enabled: true
  use_gpu: false  # 是否使用GPU加速
  language: ['ch', 'en']  # 支持的语言
  confidence_threshold: 0.5  # 置信度阈值
  
# 数据存储配置
storage:
  max_days: 30  # 数据保留天数（0表示不限制）
  deduplicate: true  # 启用图片去重
  hash_threshold: 5  # 相似度阈值（0-64，越小越严格）

# 处理配置
processing:
  batch_size: 10  # 批处理大小
  queue_size: 100  # 队列最大长度
  max_workers: 2  # 最大工作线程数
  retry_limit: 3  # 重试次数限制

# 应用黑名单（不截图的应用）
app_blacklist: []

# 隐私设置
privacy:
  blur_sensitive: false  # 模糊敏感内容
  skip_fullscreen: true  # 跳过全屏应用

# 向量数据库配置
vector_db:
  enabled: true  # 启用向量数据库
  collection_name: 'lifetrace_ocr'  # 集合名称
  embedding_model: 'shibing624/text2vec-base-chinese'  # 嵌入模型
  rerank_model: 'BAAI/bge-reranker-base'  # 重排序模型
  persist_directory: 'vector_db'  # 持久化目录
  chunk_size: 512  # 文本块大小
  chunk_overlap: 50  # 文本块重叠
  batch_size: 32  # 批处理大小
  auto_sync: true  # 自动同步
  sync_interval: 300  # 同步间隔（秒）

# 多模态配置
multimodal:
  enabled: true  # 启用多模态功能
  model_name: 'openai/clip-vit-base-patch32'  # CLIP模型名称
  text_weight: 0.6  # 文本相似度权重
  image_weight: 0.4  # 图像相似度权重
  batch_size: 16  # 批处理大小
  auto_sync: true  # 自动同步多模态向量
  sync_interval: 300  # 同步间隔（秒）

# 同步服务配置
sync_service:
  enable_file_monitor: true  # 启用文件监控
  enable_consistency_check: true  # 启用一致性检查
  consistency_check_interval: 300  # 一致性检查间隔（秒）
  vector_sync_interval: 600  # 向量同步间隔（秒）
  file_monitor_delay: 2.0  # 文件监控延迟（秒）
  cleanup_orphaned_files: true  # 清理孤立文件
  log_level: 'INFO'  # 同步服务日志级别

# 心跳监控配置
heartbeat:
  enabled: true  # 启用心跳监控
  interval: 3.0  # 心跳记录间隔（秒）
  timeout: 90  # 心跳超时时间（秒）
  check_interval: 90  # 心跳检查间隔（秒）
  log_dir: 'logs/heartbeat'  # 心跳日志目录
  
  # 日志轮转配置
  log_rotation:
    max_size_mb: 10  # 单个日志文件最大大小（MB）
    max_files: 5  # 最大日志文件数量
    auto_cleanup: true  # 自动清理旧日志
  
  # 自动重启配置
  auto_restart:
    enabled: true  # 启用自动重启
    max_attempts: 30000  # 最大重启尝试次数
    restart_delay: 5  # 重启延迟（秒）
    reset_count_interval: 3600  # 重启计数重置间隔（秒）

# 日志配置
logging:
  # 全局日志设置
  global_log_level: 'INFO'  # 全局日志级别
  enable_file_logging: true  # 启用文件日志
  enable_console_logging: true  # 启用控制台日志
  log_rotation_max_bytes: 10485760  # 日志文件最大大小（10MB）
  log_rotation_backup_count: 5  # 备份文件数量
  log_cleanup_days: 3  # 日志清理天数
  
  # 各模块日志级别
  main_log_level: 'INFO'  # 主程序日志级别
  server_log_level: 'INFO'  # 服务器日志级别
  recorder_log_level: 'INFO'  # 录制器日志级别
  processor_log_level: 'INFO'  # 处理器日志级别
  ocr_log_level: 'INFO'  # OCR日志级别
  vector_log_level: 'INFO'  # 向量数据库日志级别
  sync_log_level: 'INFO'  # 同步服务日志级别
  consistency_log_level: 'INFO'  # 一致性检查日志级别
  file_monitor_log_level: 'INFO'  # 文件监控日志级别
  
  # 调试模式设置
  debug_mode: false  # 调试模式
  debug_modules: []  # 调试模块列表